name: modern_map
description: Autonomous Modern Map module
publish_to: 'none'

version: 0.0.1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.2.2
  geolocator: ^14.0.2
  http: ^1.2.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

